author: Author name here

copyright: 2022 Author name here

dependencies:
- base >= 4.7 && < 5

executables:
  A:
    main: ./Modules/A.hs
  Templates.Contest:
    main: ./Templates/Contest.hs

ghc-options:
- -Wall
- -Wunused-packages

github: githubuser/acpoj

license: BSD3

maintainer: example@example.com

name: acpoj

version: 0.1.0.0
