dependencies:
- base >= 4.7 && < 5
- text
- managed
- directory
- bytestring

executables:
  A:
    main: ./Modules/A.hs
  Templates.Contest:
    main: ./Templates/Contest.hs

ghc-options:
- -Wall

license: BSD3

name: nix-managed

version: 0.1.0.0
