author: Author name here

copyright: 2022 Author name here

dependencies:
- base >= 4.7 && < 5

executables:
  A-exe:
    main: ./contest/A.hs

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

github: githubuser/acpoj

license: BSD3

maintainer: example@example.com

name: acpoj

version: 0.1.0.0
