author: Author name here

copyright: 2022 Author name here

dependencies:
- base >= 4.7 && < 5
- mtl
- directory
- system-filepath
- aeson
- bytestring
- text
- optparse-applicative
- filepath
- yaml
- unordered-containers
- lens-aeson
- lens
- vector
- managed

executables:
  manager:
    main: ./Main.hs
  
ghc-options:
- -Wall
- -Wunused-packages

github: githubuser/manager

license: BSD3

maintainer: example@example.com

name: manager

version: 0.1.0.0
