resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/21.yaml

ghc-options:
  "$everything":
    -Wno-missing-signatures
    -Wno-unused-top-binds
    -haddock

packages:
  - .