name: "Caching"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.guru/#30_5,17_*_*_*
    - cron: "0 0 * * *"
  pull_request:
  push:

jobs:
  cache:

    name: Build on ${{ matrix.os }}
    env:
      cache: br4ch1st0chr0n3
      devShells: (default codium)
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://hydra.iohk.io https://haskell-language-server.cachix.org https://br4ch1st0chr0n3.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8= br4ch1st0chr0n3.cachix.org-1:o1FA93L5vL4LWi+jk2ECFk1L1rDlMoTH21R1FHtSKaU=
      - uses: cachix/cachix-action@v10
        with:
          name: ${{ env.cache }}
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Push inputs to cachix
        run: |
          # https://docs.cachix.org/pushing#flakes

          nix flake archive --json \
            | jq -r '.path,(.inputs|to_entries[].value.path)' \
            | cachix push ${{ env.cache }}
      - name: Push devshells to cachix
        run: |
          for devShell in ${{ env.devShells }}
          do
            nix develop --profile dev-profile
            cachix push ${{ env.cache }} dev-profile
          end
  